language: c

compiler:
    - gcc
      #    - clang

env:
      global:
             # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
             #   via the "travis encrypt" command using the project repo's public key
             - secure: "OL++M6JOhQ4R22AGtKij3vKw2AOUapAGGb6m0TBdkO+lx0FMNOSYWOPxNDdWmC/W3hMLTq6U6avhXSsKyB1WCjtlv4QhYhmWv43dO3bN7iNIgxLa9rQ6VX8GPEUxo1mCtOgxaysb27RjW6SYTR0sRHWEaM7ZDeJ9Yja9tPULBpQ="

before_install:
     - sudo apt-get update -qq
     - sudo apt-get install -qq libconfuse-dev libarchive-dev

addons:
      coverity_scan:
             project:
                name: "fhunleth/mmccopy"
                description: "Convenient alternative to dd for writing images to SDCards"
             notification_email: fhunleth@troodon-software.com
             build_command_prepend: "./autogen.sh && ./configure"
             build_command: "make"
             branch_pattern: coverity_scan

script:
    - ./autogen.sh
    - ./configure
    - make
